definitions:
  dto.RequestAddSegmentsToUser:
    properties:
      id:
        type: integer
      segments:
        items:
          $ref: '#/definitions/service.Segment_AddSegmentsToUser'
        type: array
    required:
    - id
    - segments
    type: object
  dto.RequestCreateSegment:
    properties:
      slug:
        type: string
      user_percent:
        minimum: 0
        type: integer
    required:
    - slug
    type: object
  dto.RequestCreateUser:
    properties:
      username:
        type: string
    required:
    - username
    type: object
  dto.RequestDeleteSegment:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
  dto.RequestDeleteSegmentsFromUser:
    properties:
      id:
        type: integer
      segments:
        items:
          $ref: '#/definitions/service.Segment_DeleteSegmentsFromUser'
        type: array
    required:
    - id
    - segments
    type: object
  dto.RequestDeleteUser:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  httpresponse.Response:
    properties:
      error:
        type: string
      response: {}
      status:
        type: string
    type: object
  service.Expire:
    properties:
      days:
        minimum: 0
        type: integer
      hours:
        minimum: 0
        type: integer
      minutes:
        minimum: 0
        type: integer
    type: object
  service.Segment_AddSegmentsToUser:
    properties:
      expire:
        $ref: '#/definitions/service.Expire'
      slug:
        type: string
    required:
    - slug
    type: object
  service.Segment_DeleteSegmentsFromUser:
    properties:
      slug:
        type: string
    required:
    - slug
    type: object
info:
  contact: {}
paths:
  /history:
    get:
      consumes:
      - application/json
      description: Возвращает историю добавления/удаления сегментов  в виде csv файла.Принимает
        id пользователя и период времени .Если указан user_id , то возвращает историю
        конкретного пользователя, иначе - все историю заданного периода
      parameters:
      - description: user_id
        in: query
        name: user_id
        type: integer
      - description: Месяц
        in: query
        name: month
        required: true
        type: string
      - description: Год
        in: query
        name: year
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: GetHistory
      tags:
      - History
  /segment:
    delete:
      consumes:
      - application/json
      description: Удаляет сегмент.Принимает slug сегмента
      parameters:
      - description: slug
        in: body
        name: slug
        required: true
        schema:
          $ref: '#/definitions/dto.RequestDeleteSegment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: DeleteSegment
      tags:
      - Segment
  /segment/new:
    post:
      consumes:
      - application/json
      description: Создает сегмент.Принимает slug сегмента и процент пользоватей,которым
        он присвоится.Если указан user_percent,то добавит созданный сегмент указанному
        проценту пользователей(округление идет в большую сторону) , добавит запись
        в history и вернет id пользователей,котором добавили созданный сегмент.Если
        такой сегмент уже существует,то выведет соответствующую ошибку.
      parameters:
      - description: slug
        in: body
        name: slug
        required: true
        schema:
          $ref: '#/definitions/dto.RequestCreateSegment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: CreateSegment
      tags:
      - Segment
  /user:
    delete:
      consumes:
      - application/json
      description: Удаляет пользователя.Принимает Id пользователя
      parameters:
      - description: id
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/dto.RequestDeleteUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: DeleteUser
      tags:
      - User
  /user/new:
    post:
      consumes:
      - application/json
      description: Создает пользователя.Принимает имя пользователя.Если такой пользователь
        уже существует,то выведете соответствующую ошибку.
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          $ref: '#/definitions/dto.RequestCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: CreateUser
      tags:
      - User
  /user/segments:
    delete:
      consumes:
      - application/json
      description: Удаляет сегменты пользователя.Принимает slug сегмента.Если у сегмента
        был TTL, то удаляет его из кэша.Также добавляет запись удаления в history
      parameters:
      - description: id
        in: body
        name: segments
        required: true
        schema:
          $ref: '#/definitions/dto.RequestDeleteSegmentsFromUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: DeleteSegmentsFromUser
      tags:
      - User
  /user/segments/{id}:
    get:
      consumes:
      - application/json
      description: Возвращает сегметы пользовател.Принимает id пользователя
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: GetUsersSegments
      tags:
      - User
  /user/segments/add:
    post:
      consumes:
      - application/json
      description: Добавляет сегменты пользователю.Принимает id пользователя и сегменты
        с полями slug и expire.Если в сегментах указаны expire,то добавляет заданным
        сегментам TTL.Также добавляет запись добавления в history
      parameters:
      - description: id
        in: body
        name: segments
        required: true
        schema:
          $ref: '#/definitions/dto.RequestAddSegmentsToUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httpresponse.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httpresponse.Response'
      summary: AddSegmentsToUser
      tags:
      - User
swagger: "2.0"
